
config:
  target: 'http://localhost:8082'
  phases:
    - duration: 30
      arrivalRate: 2


scenarios:
  - name: Flow de trabajo normal ECommerce
    flow:
    - loop:
        - post:
            url: "/api/sessions/login"
        - post:
            url: "/api/products"
        - delete:
            url: "/api/products"
        - get:
            url: "/api/sessions/logout"
      count: 10